
enableEmoji = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

defaultContentLanguage = "en"
languageCode = "en"
#googleAnalytics = "G-6W0F36B62E"
Title = "Techweb Unraveled"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[params]
  
  giscusTheme="preferred_color_scheme"
  disableComments=false

  enableCDN = true
  optimizeImages = true

  # URL for the avatar on homepage
  avatarURL = "/images/logo.webp"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-xs"
  dateFormat = "2 January, 2006"
  
  # Description to display on homepage
  description = "One thread at the time"
    
  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"
  accentColorDark = "#007FFF"

  # Display "back to top" button on posts
  ShowBackToTopButton = true

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""
  highlightCode = true
  socialIcons = [
    {name = "twitter", url = "https://twitter.com/mohd_somayyah"},
    {name = "youtube", url = "https://www.youtube.com/channel/UCV91hFH6IHsl6-sxbLmMtfA"},
    {name = "email", url = "mailto:watari@techwebunraveled.xyz"},
    {name = "bsky", url = "https://bsky.app/profile/watariuiuiuizifa.bsky.social"}
  ]

  # Keywords relevant for SEO
  metaKeywords = []

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  showPostsOnHomePage = "popular"

  # Footer text
  footer = "watari@techwebunraveled.xyz"

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"
    url = "/posts/"

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
      identifier = "projects"
      url = "/projects/"
      weight = 3
      
      # We use feather-icons: https://feathericons.com/
      pre = "<span data-feather='archive'></span>"
  
  [[menu.main]]
      identifier = "portal"
      url = "/portal/"
      weight = 5
      # We use feather-icons: https://feathericons.com/
      pre = "<span data-feather='key'></span>"

  [[menu.main]]
    identifier = "github"
    url = "https://github.com/Somayyah"
    weight = 6
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"

  [[menu.main]]
      identifier = "Side Ventures"
      url = "/side-ventures/"
      weight = 7
      
      # We use feather-icons: https://feathericons.com/
      pre = "<span data-feather='aperture'></span>"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[minify]
  disableCSS = false
  disableJS = false
  disableHTML = false

[build]
  minify = true